---
output:
  pdf_document: default
  html_document: default
---
# TDF Exploration

## Brian Richardson
## 09/14/2022

In this program we do exploratory data analysis on the TDF data


```{r setup, echo=F, message=F, warning=F}
# Prepare workspace
rm(list=ls())

library(ggplot2)
library(tidyr)
library(dplyr)
library(tinytex)

```

```{r load-data}

riders <- read.csv("derived-data/TDF_Riders_History_Clean.csv")

stages <- read.csv("derived-data/TDF_Stages_History_Clean.csv")

```

```{r stages-plots}

# Number of stages per year
stages %>% 
  group_by(year) %>% 
  count() %>% 
  ggplot(aes(x = year, y = n)) +
  geom_line() +
  ggtitle("Number of Stages per Year Over Time") +
  xlab("Year") +
  ylab("Number of Stages") -> stages_per_year_plot

# Examine common starting and ending locations
stages %>% 
  group_by(start_loc) %>% 
  count() %>% 
  filter(n >= 20) %>% 
  #arrange(n) %>% 
  ggplot(aes(y = reorder(start_loc, (-n)), x = n)) +
  geom_bar(stat='identity') +
  ggtitle("Popular Starting and Ending Locations")


stages %>% 
  select(start_loc, end_loc) %>% 
  pivot_longer(cols = c(start_loc, end_loc),
               names_to = "start_end",
               values_to = "loc") %>% 
  group_by(start_end, loc) %>% 
  count() %>% 
  filter(n >= 30) %>% 
  ggplot(aes(y = reorder(loc, (-n)), x = n)) +
  geom_bar(stat='identity') +
  facet_wrap(~ start_end) +
  ggtitle("Popular Starting and Ending Locations")


```

```{r riders-plot}

# Add a variables for total hours and average km/hr
riders <- riders %>% 
  mutate(totalhours = totalseconds / 3600,
         avg_speed = distance_km / totalhours)

# Plot total distance ridden for each rider for each year
ggplot(riders, aes(x = year, y = distance_km, color = rider)) +
  geom_point() +
  theme(legend.position = "none") +
  ggtitle("Total Distance over Years") +
  xlab("Year") +
  ylab("Total Distance (km)")

# Plot total hours ridden for each rider for each year
ggplot(riders, aes(x = year, y = totalhours, color = rider)) +
  geom_point() +
  theme(legend.position = "none") +
  ggtitle("Total Hours Ridden over Years") +
  xlab("Year") +
  ylab("Riding Time (Hours)")

# Plot average speed over years
ggplot(riders, aes(x = year, y = avg_speed, color = rider)) +
  geom_point() +
  theme(legend.position = "none") +
  ggtitle("Average Speed over Years") +
  xlab("Year") +
  ylab("Average Speed (km/hr)")
  


```

